export const GET_TONAL_STATE = 'GET_TONAL_STATE';
export const GET_CHORD_NAMES = 'GET_CHORD_NAMES';
export const UPDATE_KEY = 'UPDATE_KEY';
export const UPDATE_SCALE = 'UPDATE_SCALE';
export const UPDATE_OCTAVE = 'UPDATE_OCTAVE';
export const UPDATE_SCALE_TYPE = 'UPDATE_SCALE_TYPE'
